tiers:
  common:
    name: "Common"
    level: 1
    chance: 50
    color: "&7"
    min-quality: 0
    max-quality: 30
    permissions:
      - "tier.common"
  uncommon:
    name: "Uncommon"
    level: 2
    chance: 30
    color: "&a"
    min-quality: 20
    max-quality: 50
    permissions:
      - "tier.uncommon"
  rare:
    name: "Rare"
    level: 3
    chance: 15
    color: "&9"
    min-quality: 40
    max-quality: 70
    permissions:
      - "tier.rare"
  epic:
    name: "Epic"
    level: 4
    chance: 4
    color: "&5"
    min-quality: 60
    max-quality: 85
    permissions:
      - "tier.epic"
  legendary:
    name: "Legendary"
    level: 5
    chance: 1
    color: "&6"
    min-quality: 80
    max-quality: 100
    permissions:
      - "tier.legendary"

# Items that can receive tiers
tierable-items:
  tools:
    - WOODEN_PICKAXE
    - STONE_PICKAXE
    - IRON_PICKAXE
    - GOLDEN_PICKAXE
    - DIAMOND_PICKAXE
    - NETHERITE_PICKAXE
    - WOODEN_AXE
    - STONE_AXE
    - IRON_AXE
    - GOLDEN_AXE
    - DIAMOND_AXE
    - NETHERITE_AXE
    - WOODEN_SHOVEL
    - STONE_SHOVEL
    - IRON_SHOVEL
    - GOLDEN_SHOVEL
    - DIAMOND_SHOVEL
    - NETHERITE_SHOVEL
    - WOODEN_HOE
    - STONE_HOE
    - IRON_HOE
    - GOLDEN_HOE
    - DIAMOND_HOE
    - NETHERITE_HOE
  weapons:
    - WOODEN_SWORD
    - STONE_SWORD
    - IRON_SWORD
    - GOLDEN_SWORD
    - DIAMOND_SWORD
    - NETHERITE_SWORD
    - BOW
    - CROSSBOW
    - TRIDENT
  armor:
    - LEATHER_HELMET
    - LEATHER_CHESTPLATE
    - LEATHER_LEGGINGS
    - LEATHER_BOOTS
    - CHAINMAIL_HELMET
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_LEGGINGS
    - CHAINMAIL_BOOTS
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS
    - GOLDEN_HELMET
    - GOLDEN_CHESTPLATE
    - GOLDEN_LEGGINGS
    - GOLDEN_BOOTS
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - NETHERITE_HELMET
    - NETHERITE_CHESTPLATE
    - NETHERITE_LEGGINGS
    - NETHERITE_BOOTS
    - ELYTRA 