name: TierTools
version: '${project.version}'
main: fun.mntale.tierTools.TierTools
api-version: '1.20'
authors: [mntale]
folia-supported: true
description: A plugin for managing item tiers and attributes
commands:
  tiertools:
    description: Main command for TierTools plugin
    usage: /<command> [reload]
    aliases: [tt]
    permission: tiertools.admin
    permission-message: You don't have permission to use this command!
permissions:
  tiertools.admin:
    description: Gives access to all TierTools commands
    default: op
  tiertools.reload:
    description: Allows reloading the plugin configuration
    default: op
  tier.common:
    description: Allows using common tier items
    default: true
  tier.uncommon:
    description: Allows using uncommon tier items
    default: true
  tier.rare:
    description: Allows using rare tier items
    default: true
  tier.epic:
    description: Allows using epic tier items
    default: true
  tier.legendary:
    description: Allows using legendary tier items
    default: true